#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use Config;
use English qw(-no_match_vars);

use Pod::Usage;
use File::Copy;
use Getopt::Long qw(GetOptions);

use version; our $VERSION = qv('0.0.1');

# Default column width
our $DEFAULT_COLUMN_WIDTH = 80;
our $DO_BACKUP = 0;
our $file_to_fold = undef;

sub main {
    my $help;

    GetOptions(
        # 'width=w' => \$DEFAULT_COLUMN_WIDTH,
        # 'backup=b' => \$DO_BACKUP,
        'help' => \$help,
        'version' => sub {
            print "foldo v$VERSION\n";
            exit;
        }
    ) or die "Usage: $0 --file <file> [--help] [--version]\n";

    if (defined $help) {
        print "Usage: $EXECUTABLE_NAME [options] FILE\n";
        print "Options:\n";
        print "  --help           Print this help message\n";
        print "  --version        Print the version number\n";
        exit;
    }

    if (@ARGV != 1) {
        print "Error: no file specified\n";
        die "Usage: $EXECUTABLE_NAME [options] FILE\n";
    }

    foreach my $line (read_file_lines($ARGV[0])) {
        print $line
    }
}

sub read_file_lines {
    my ($my_file) = @_;
    open(my $fh, '<:encoding(UTF-8)', $my_file) or die "Could not open file '$my_file' $!";
    my @lines = <$fh>;
    close($fh);
    return @lines;
}

main();
